[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013069F5C690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ed4361d5c1f90c8cbd0324c42d6f542c/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013069F5DAD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ed4361d5c1f90c8cbd0324c42d6f542c/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013069F5EED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ed4361d5c1f90c8cbd0324c42d6f542c/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013069D53410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ed4361d5c1f90c8cbd0324c42d6f542c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013069D51E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ed4361d5c1f90c8cbd0324c42d6f542c
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013069D52910>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ed4361d5c1f90c8cbd0324c42d6f542c