[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AC4B743FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bde853878fecd4c3c37642c34c5bd72b/execute/sync
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AC4B6DAB90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bde853878fecd4c3c37642c34c5bd72b/execute/sync
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AC4B6ED210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/bde853878fecd4c3c37642c34c5bd72b/execute/sync